### ISSUE TITLE
Hay forma de usar esto para descargar todo el sitio y tener una copia local?

### ISSUE THREAD

**Issue by banjorae** [Verdoso/epl_librarian#111]
No encuentro nada parecido por ningun lado

**Comment by Verdoso** [comment]
Hola,
No, para descargar el sitio completo existe un plugin de Calibre ([Biblioteca EPL (plugin para Calibre)](https://www.epublibre.org/foro/viewtopic.php?f=8&t=49914)).
epl_librarian sirve para revisar el catálogo y controlar únicamente los que te interesan, no para descargarlo todo.

**Comment by 9acca9** [comment]
Ok, muchas gracias! Y gracias por el trabajo que hacen!!!
