### ISSUE TITLE
Dejar que sea accesible desde otra pc

### ISSUE THREAD

**Issue by 9acca9** [Verdoso/epl_librarian#115]
Hola.
Uso un servidor y quisiera instalar el programa en uno de los contenedores.

Podrías permitir modificar la url?

De esa manera podría acceder desde otra pc y dejarlo corriendo siempre en mi servidor.
Te agradezco.

**Comment by 9acca9** [comment]
es accesible desde otra pc así como está.

**Comment by Verdoso** [comment]
Si, simplemente hace falta apuntar a la IP/nombre que sea accesible desde el otro ordenador.
