### ISSUE TITLE
que se agreguen los magnet en el servidor en que se ejecuta el servicio

### ISSUE THREAD

**Issue by 9acca9** [Verdoso/epl_librarian#116]
Hola.
Quería pedir si fuera posible incorporar la descarga de los libros directamente en la pc en que se está ejecutando epl librarian.
(o poner todos los magnet en un archivo de texto que luego yo subiría manualmente a un servidor de descarga de torrents)

Me resulta apropiado e interesante para mi caso poder correr EPL librarian en un contenedor headless en Proxmox.

Actualmente lo acabo de instalar y puedo acceder al mismo desde otra pc. Por lo que eso funciona perfecto, pero al poner descargar lo que sucede es que se me abre el cuadro de diálogo de descarga desde la pc que lo visito. Es decir, en donde se ejecuta el navegador.

En otro orden de cosas:

Lo que yo hacía habitualmente era utilizar un plugin para Calibre pero luego de que se me rompió la compu estoy viendo de correr todo desde proxmox. (hice backup por lo que cuento con una versión bastante actualizada de hace un par de meses de los libros de EPL)

Será posible poner a descargar todos los libros que no tengo en mi biblioteca a la vez con EPL librarian? 

Muchas gracias!

**Comment by Verdoso** [comment]
Hola,
Respecto a la primera parte, la aplicación esta pensada para usarse como cliente. Respecto a comunicarse directamente con un programa de torrents, aparte de que no lo uso para eso, el problema es que no hay un API genérico para ello y cada uno tiene el suyo propio. Y hacer uno específico para cada programa de torrent y luego mantenerlos... mucho trabajo para un caso muy concreto.
En cuanto a descargar los libros, lo único que se podría hacer es exportar al portapapeles los enlaces de todos los que tengas en la tabla en ese momento. Si filtras quitando los que no tienes... eso podría servir. Eso sí, epl_librarian no hace control de versiones así que no detecta si tienes una versión antigua de un libro.
Para tener una replica en Calibre de todo lo que hay en EpubLibre es mejor usar el plugin del Calibre que está hecho para eso. EPL Librarían es para descargarse solo algunos libros.

**Comment by 9acca9** [comment]
Ok, muchísimas gracias, lo tendré en cuenta!
Y muchas gracias por compartir tu trabajo!
